import io
import json
import uuid

from flask import render_template, send_file, request, flash, redirect, url_for, session, current_app
from sqlalchemy import func
from stitch.blueprints.admin import bp
from stitch.blueprints.auth.routes import login_required, admin_required
from stitch.database import db
from stitch.models.user import User
from stitch.models.color import Color
from stitch.models.project import Project, ProjectStatus
from stitch.services.project_service import ProjectService, CHART_SYMBOLS


@bp.route('/')
@login_required
@admin_required
def dashboard():
    """Admin dashboard with platform metrics"""
    total_users = db.session.query(func.count(User.id)).scalar()
    total_projects = db.session.query(func.count(Project.id)).filter(
        Project.status != ProjectStatus.DELETED
    ).scalar()

    return render_template('admin/dashboard.html',
                           total_users=total_users,
                           total_projects=total_projects)


@bp.route('/users')
@login_required
@admin_required
def users():
    """List all users"""
    all_users = db.session.query(
        User,
        func.count(Project.id).label('project_count')
    ).outerjoin(
        Project,
        (User.id == Project.user_id) & (Project.status != ProjectStatus.DELETED)
    ).group_by(User.id).order_by(User.created_at.desc()).all()

    return render_template('admin/users.html', users=all_users)


@bp.route('/users/<user_id>')
@login_required
@admin_required
def user_detail(user_id):
    """Admin user detail page with their projects"""
    user = User.query.get(user_id)
    if not user:
        flash('User not found.', 'warning')
        return redirect(url_for('admin.users'))

    user_projects = Project.query.filter(
        Project.user_id == user_id,
        Project.status != ProjectStatus.DELETED,
    ).order_by(Project.created_at.desc()).all()

    return render_template('admin/user_detail.html',
                           user=user,
                           projects=user_projects,
                           ProjectStatus=ProjectStatus)


@bp.route('/projects')
@login_required
@admin_required
def projects():
    """List all projects"""
    all_projects = db.session.query(Project, User).outerjoin(
        User, Project.user_id == User.id
    ).filter(
        Project.status != ProjectStatus.DELETED
    ).order_by(Project.created_at.desc()).all()

    return render_template('admin/projects.html',
                           projects=all_projects,
                           ProjectStatus=ProjectStatus)


@bp.route('/projects/<project_id>')
@login_required
@admin_required
def project_detail(project_id):
    """Admin project detail page with large thumbnail"""
    project = Project.query.get(project_id)
    if not project:
        return render_template('admin/project_detail.html', project=None), 404

    owner = User.query.get(project.user_id) if project.user_id else None

    return render_template('admin/project_detail.html',
                           project=project,
                           owner=owner,
                           ProjectStatus=ProjectStatus)


@bp.route('/projects/<project_id>/thumbnail-large')
@login_required
@admin_required
def project_thumbnail_large(project_id):
    """Serve large thumbnail for any project (admin bypass)"""
    from stitch.services.pattern_renderer import PatternRenderer
    import cv2

    project = Project.query.get(project_id)
    if not project:
        return '', 404

    try:
        state = ProjectService.assemble_state(project)
        thumb = PatternRenderer.render_thumbnail(
            state, project.width, project.height
        )

        thumb_bgr = cv2.cvtColor(thumb, cv2.COLOR_RGB2BGR)
        success, buffer = cv2.imencode('.png', thumb_bgr)

        if not success:
            return '', 500

        return send_file(
            io.BytesIO(buffer.tobytes()),
            mimetype='image/png',
            as_attachment=False
        )

    except Exception:
        return '', 500


@bp.route('/import-pattern', methods=['GET', 'POST'])
@login_required
@admin_required
def import_pattern():
    """Import a cross-stitch pattern from JSON (generated by an LLM)"""
    if request.method == 'POST':
        raw_json = request.form.get('pattern_json', '').strip()

        if not raw_json:
            flash('Please paste the pattern JSON.', 'danger')
            return render_template('admin/import_pattern.html', pattern_json=raw_json)

        try:
            data = json.loads(raw_json)
        except json.JSONDecodeError as e:
            flash(f'Invalid JSON: {e}', 'danger')
            return render_template('admin/import_pattern.html', pattern_json=raw_json)

        # Validate required fields
        errors = _validate_pattern_json(data)
        if errors:
            for err in errors:
                flash(err, 'danger')
            return render_template('admin/import_pattern.html', pattern_json=raw_json)

        # Look up DMC colors
        color_map = data['colors']
        dmc_lookup = {}  # alias -> Color record
        for alias, dmc_code in color_map.items():
            if dmc_code is None:
                continue
            color_record = Color.query.filter_by(vendor='DMC', code=str(dmc_code)).first()
            if not color_record:
                flash(f'DMC color code "{dmc_code}" (alias "{alias}") not found in catalog.', 'danger')
                return render_template('admin/import_pattern.html', pattern_json=raw_json)
            dmc_lookup[alias] = color_record

        # Build palette with pre-generated UUIDs
        palette_colors = []  # list of {uuid, color_record, symbol}
        alias_to_uuid = {}
        for idx, (alias, color_record) in enumerate(dmc_lookup.items()):
            color_uuid = str(uuid.uuid4())
            symbol = CHART_SYMBOLS[idx] if idx < len(CHART_SYMBOLS) else '?'
            palette_colors.append({
                'uuid': color_uuid,
                'color': color_record,
                'symbol': symbol,
            })
            alias_to_uuid[alias] = color_uuid

        width = data['width']
        height = data['height']

        # Build cells from grid (full stitches)
        cells = {}
        for y, row in enumerate(data['grid']):
            for x, ch in enumerate(row):
                if ch in alias_to_uuid:
                    cell_key = f"{x},{y}"
                    cells[cell_key] = [{'color': alias_to_uuid[ch], 'stitch': 'full'}]

        # Three-quarter stitches
        _CORNER_TO_STITCH = {
            'tl': 'three-quarter-tl', 'tr': 'three-quarter-tr',
            'bl': 'three-quarter-bl', 'br': 'three-quarter-br',
        }
        for entry in data.get('three_quarter_stitches', []):
            cell_key = f"{entry['x']},{entry['y']}"
            color_uuid = alias_to_uuid[entry['color']]
            stitch_type = _CORNER_TO_STITCH[entry['corner']]
            cells.setdefault(cell_key, []).append({'color': color_uuid, 'stitch': stitch_type})

        # Half stitches
        _DIR_TO_STITCH = {'/': 'half-slash', '\\': 'half-backslash'}
        for entry in data.get('half_stitches', []):
            cell_key = f"{entry['x']},{entry['y']}"
            color_uuid = alias_to_uuid[entry['color']]
            stitch_type = _DIR_TO_STITCH[entry['direction']]
            cells.setdefault(cell_key, []).append({'color': color_uuid, 'stitch': stitch_type})

        # Quarter stitches
        _QUARTER_TO_STITCH = {
            'tl': 'quarter-tl', 'tr': 'quarter-tr',
            'bl': 'quarter-bl', 'br': 'quarter-br',
        }
        for entry in data.get('quarter_stitches', []):
            cell_key = f"{entry['x']},{entry['y']}"
            color_uuid = alias_to_uuid[entry['color']]
            stitch_type = _QUARTER_TO_STITCH[entry['corner']]
            cells.setdefault(cell_key, []).append({'color': color_uuid, 'stitch': stitch_type})

        # Back stitches (lines) → paths array
        paths = []
        for entry in data.get('back_stitches', []):
            paths.append({
                'startX': entry['startX'],
                'startY': entry['startY'],
                'endX': entry['endX'],
                'endY': entry['endY'],
                'color': alias_to_uuid[entry['color']],
                'stitch': 'line',
            })

        # Create project
        name = data.get('name', 'Imported Pattern')
        description = data.get('description', '')
        user_id = session.get('user_id')

        project = ProjectService.create_project(
            user_id=user_id,
            name=name,
            width=width,
            height=height,
            description=description,
        )

        # Build save data in save_project_data format
        layer_id = str(uuid.uuid4())
        save_data = {
            'activeLayerId': layer_id,
            'colors': [
                {
                    'id': pc['uuid'],
                    'vendor': 'DMC',
                    'code': pc['color'].code,
                    'symbol': pc['symbol'],
                }
                for pc in palette_colors
            ],
            'layers': [
                {
                    'id': layer_id,
                    'type': 'raster',
                    'name': 'Main stitches',
                    'visible': True,
                    'activeForExport': True,
                    'editable': True,
                    'sortOrder': 0,
                    'cells': cells,
                    'paths': paths,
                }
            ],
            'properties': {
                'majorGridInterval': current_app.config.get('MAJOR_GRID_INTERVAL', 5),
                'showGridNumbers': False,
                'defaultStitchType': 'full',
            }
        }

        ProjectService.save_project_data(project, save_data)

        flash(f'Pattern "{name}" imported successfully ({width}x{height}, {len(palette_colors)} colors).', 'success')
        return redirect(url_for('admin.project_detail', project_id=project.id))

    return render_template('admin/import_pattern.html', pattern_json='')


# Valid corners and directions for stitch validation
_VALID_CORNERS = {'tl', 'tr', 'bl', 'br'}
_VALID_HALF_DIRS = {'/', '\\'}


def _validate_pattern_json(data: dict) -> list[str]:
    """Validate the pattern JSON structure. Returns list of error messages."""
    errors = []

    if not isinstance(data, dict):
        return ['JSON must be an object.']

    for field in ('name', 'width', 'height', 'colors', 'grid'):
        if field not in data:
            errors.append(f'Missing required field: "{field}".')

    if errors:
        return errors

    if not isinstance(data['width'], int) or data['width'] < 1 or data['width'] > 1000:
        errors.append('Width must be an integer between 1 and 1000.')

    if not isinstance(data['height'], int) or data['height'] < 1 or data['height'] > 1000:
        errors.append('Height must be an integer between 1 and 1000.')

    if not isinstance(data['colors'], dict):
        errors.append('"colors" must be an object mapping aliases to DMC codes.')

    if not isinstance(data['grid'], list):
        errors.append('"grid" must be an array of strings.')

    if errors:
        return errors

    width = data['width']
    height = data['height']
    grid = data['grid']
    all_aliases = set(data['colors'].keys())
    color_aliases = {k for k, v in data['colors'].items() if v is not None}

    # Grid validation
    if len(grid) != height:
        errors.append(f'Grid has {len(grid)} rows but height is {height}.')

    for i, row in enumerate(grid):
        if not isinstance(row, str):
            errors.append(f'Grid row {i} must be a string.')
        elif len(row) != width:
            errors.append(f'Grid row {i} has {len(row)} characters but width is {width}.')

    for i, row in enumerate(grid):
        if not isinstance(row, str):
            continue
        for ch in row:
            if ch not in all_aliases:
                errors.append(f'Grid character "{ch}" (row {i}) has no color mapping.')
                break

    # Three-quarter stitches validation
    for i, entry in enumerate(data.get('three_quarter_stitches', [])):
        prefix = f'three_quarter_stitches[{i}]'
        errors.extend(_validate_cell_stitch(entry, prefix, width, height, color_aliases, 'corner', _VALID_CORNERS))

    # Half stitches validation
    for i, entry in enumerate(data.get('half_stitches', [])):
        prefix = f'half_stitches[{i}]'
        errors.extend(_validate_cell_stitch(entry, prefix, width, height, color_aliases, 'direction', _VALID_HALF_DIRS))

    # Quarter stitches validation
    for i, entry in enumerate(data.get('quarter_stitches', [])):
        prefix = f'quarter_stitches[{i}]'
        errors.extend(_validate_cell_stitch(entry, prefix, width, height, color_aliases, 'corner', _VALID_CORNERS))

    # Back stitches (lines) validation — coordinates are grid corners (0..W, 0..H inclusive)
    for i, entry in enumerate(data.get('back_stitches', [])):
        prefix = f'back_stitches[{i}]'
        if not isinstance(entry, dict):
            errors.append(f'{prefix}: must be an object.')
            continue
        for field in ('startX', 'startY', 'endX', 'endY', 'color'):
            if field not in entry:
                errors.append(f'{prefix}: missing "{field}".')
        if errors:
            continue
        for coord, max_val, axis in [
            ('startX', width, 'X'), ('endX', width, 'X'),
            ('startY', height, 'Y'), ('endY', height, 'Y'),
        ]:
            v = entry[coord]
            if not isinstance(v, int) or v < 0 or v > max_val:
                errors.append(f'{prefix}: {coord} must be 0..{max_val} (grid corner).')
        if entry.get('color') not in color_aliases:
            errors.append(f'{prefix}: color "{entry.get("color")}" is not a valid color alias.')

    # Check for too many colors
    if len(color_aliases) > 128:
        errors.append(f'Too many colors ({len(color_aliases)}). Maximum is 128.')

    return errors


def _validate_cell_stitch(entry: dict, prefix: str, width: int, height: int,
                          color_aliases: set, variant_field: str, valid_values: set) -> list[str]:
    """Validate a single cell-based stitch entry (three-quarter, half, quarter)."""
    errors = []
    if not isinstance(entry, dict):
        errors.append(f'{prefix}: must be an object.')
        return errors
    for field in ('x', 'y', 'color', variant_field):
        if field not in entry:
            errors.append(f'{prefix}: missing "{field}".')
    if errors:
        return errors
    x, y = entry['x'], entry['y']
    if not isinstance(x, int) or x < 0 or x >= width:
        errors.append(f'{prefix}: x must be 0..{width - 1}.')
    if not isinstance(y, int) or y < 0 or y >= height:
        errors.append(f'{prefix}: y must be 0..{height - 1}.')
    if entry['color'] not in color_aliases:
        errors.append(f'{prefix}: color "{entry["color"]}" is not a valid color alias.')
    if entry[variant_field] not in valid_values:
        errors.append(f'{prefix}: {variant_field} must be one of {sorted(valid_values)}.')
    return errors
